---
sidebar: sidebar 
permalink: oracle/aws-ora-fsx-ec2-deploy-intro.html 
summary: 'Ce livre blanc fournit un aperçu et une validation d"une solution pour la base de données Oracle RDS HA et DR personnalisée AWS, exploitant le service de stockage AWS FSx dans un déploiement multi-zones de disponibilité.' 
keywords: HA, DR, database, Oracle, RDS, AWS 
---
= WP-7357 : Introduction aux meilleures pratiques de déploiement de bases de données Oracle sur EC2 et FSx
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Allen Cao, Niyaz Mohamed, Jeffrey Steiner, NetApp

[role="lead"]
De nombreuses bases de données Oracle d’entreprise critiques sont toujours hébergées sur site, et de nombreuses entreprises cherchent à migrer ces bases de données Oracle vers un cloud public.  Souvent, ces bases de données Oracle sont centrées sur les applications et nécessitent donc des configurations spécifiques à l'utilisateur, une capacité qui manque à de nombreuses offres de cloud public de base de données en tant que service.  Par conséquent, le paysage actuel des bases de données nécessite une solution de base de données Oracle basée sur le cloud public, construite à partir d'un service de calcul et de stockage hautes performances et évolutif, capable de répondre à des exigences uniques.  Les instances de calcul AWS EC2 et le service de stockage AWS FSx pourraient être les pièces manquantes de ce puzzle que vous pouvez exploiter pour créer et migrer vos charges de travail de base de données Oracle critiques vers un cloud public.

Amazon Elastic Compute Cloud (Amazon EC2) est un service Web qui fournit une capacité de calcul sécurisée et redimensionnable dans le cloud.  Il est conçu pour faciliter le cloud computing à l’échelle du Web pour les entreprises.  L'interface simple du service Web Amazon EC2 vous permet d'obtenir et de configurer la capacité avec un minimum de friction.  Il vous offre un contrôle complet de vos ressources informatiques et vous permet d'exécuter l'environnement informatique éprouvé d'Amazon.

Amazon FSx ONTAP est un service de stockage AWS qui utilise le stockage de blocs et de fichiers NetApp ONTAP , leader du secteur, qui expose NFS, SMB et iSCSI.  Avec un moteur de stockage aussi puissant, il n'a jamais été aussi simple de déplacer des applications de base de données Oracle critiques vers AWS avec des temps de réponse inférieurs à la milliseconde, plusieurs Go/s de débit et plus de 100 000 IOPS par instance de base de données.  Mieux encore, le service de stockage FSx est doté d'une capacité de réplication native qui vous permet de migrer facilement votre base de données Oracle sur site vers AWS ou de répliquer votre base de données Oracle critique vers une zone de disponibilité AWS secondaire pour HA ou DR.

L'objectif de cette documentation est de fournir des processus, des procédures et des conseils de bonnes pratiques étape par étape sur la manière de déployer et de configurer une base de données Oracle avec un stockage FSx et une instance EC2 qui offre des performances similaires à celles d'un système sur site.  NetApp fournit également une boîte à outils d’automatisation qui automatise la plupart des tâches requises pour le déploiement, la configuration et la gestion de votre charge de travail de base de données Oracle dans le cloud public AWS.

Pour en savoir plus sur la solution et le cas d'utilisation, regardez la vidéo de présentation suivante :

link:https://www.netapp.tv/insight/details/30000?playlist_id=275&mcid=04891225598830484314259903524057913910["Modernisez votre base de données Oracle avec le cloud hybride dans AWS et FSx ONTAP, Partie 1 - Cas d'utilisation et architecture de la solution"^]
