---
sidebar: sidebar 
permalink: oracle/azure-ora-nfile-usecase.html 
summary: Ce guide des meilleures pratiques fournit des détails sur une solution de déploiement et de migration de la base de données Oracle sur le stockage de fichiers Azure NetApp et la machine virtuelle Azure. 
keywords: database, Oracle, Azure NetApp files, Azure 
---
= TR-4954 : Meilleures pratiques de déploiement et de migration de bases de données Oracle pour ANF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce guide des meilleures pratiques fournit des détails sur une solution de déploiement et de migration de la base de données Oracle sur le stockage de fichiers Azure NetApp et la machine virtuelle Azure.



== Aperçu

De nombreuses bases de données d’entreprise Oracle critiques sont toujours hébergées sur site, et de nombreuses entreprises cherchent à migrer ces bases de données Oracle vers un cloud public.  Souvent, ces bases de données Oracle sont centrées sur les applications et nécessitent donc des configurations spécifiques à l'utilisateur, une capacité qui manque à de nombreuses offres de cloud public de base de données en tant que service.  Par conséquent, le paysage actuel des bases de données nécessite une solution de base de données Oracle basée sur le cloud public, construite à partir d'un service de calcul et de stockage hautes performances et évolutif, capable de répondre à des exigences uniques.  Les instances de calcul de machine virtuelle Azure et le service de stockage Azure NetApp Files pourraient être les pièces manquantes de ce puzzle que vous pouvez exploiter pour créer et migrer vos charges de travail de base de données Oracle critiques vers un cloud public.



== Machine virtuelle Azure

Les machines virtuelles Azure sont l’un des nombreux types de ressources informatiques évolutives à la demande proposées par Azure.  En règle générale, vous choisissez une machine virtuelle lorsque vous avez besoin de plus de contrôle sur l’environnement informatique que ce que les autres choix offrent.  Les machines virtuelles Azure offrent un moyen rapide et simple de créer un ordinateur avec des configurations spécifiques requises pour exécuter votre base de données Oracle, qu’il s’agisse de charges de travail gourmandes en calcul ou en mémoire.  Les machines virtuelles d’un réseau virtuel Azure peuvent facilement être connectées au réseau de votre organisation, par exemple via un tunnel VPN sécurisé.



== Azure NetApp Files (ANF)

Azure NetApp Files est un service Microsoft entièrement géré qui transférera votre charge de travail de base de données vers le cloud plus rapidement et en toute sécurité que jamais.  Il a été conçu pour répondre aux exigences de base de l'exécution de charges de travail hautes performances telles que les bases de données Oracle dans le cloud, et il fournit des niveaux de performances qui reflètent la gamme réelle des demandes d'IOPS, une faible latence, une haute disponibilité, une durabilité élevée, une facilité de gestion à grande échelle et une sauvegarde, une récupération et un clonage rapides et efficaces.  Ces fonctionnalités sont possibles car Azure NetApp Files est basé sur des systèmes NetApp ONTAP entièrement flash physiques exécutés dans l’environnement du centre de données Azure.  Azure NetApp Files est entièrement intégré aux contrôleurs de domaine et au portail Azure, et les clients peuvent utiliser la même interface graphique et les mêmes API confortables pour créer et gérer des fichiers partagés qu’avec tout autre objet Azure.  Avec Azure NetApp File, vous pouvez exploiter toutes les fonctionnalités d’Azure sans risque, coût ou temps supplémentaire et faire confiance au seul service de fichiers d’entreprise natif d’Azure.



== Conclusion

Cette documentation décrit en détail comment déployer, configurer et migrer une base de données Oracle avec une machine virtuelle Azure et un service de stockage Azure NetApp Files qui offre des performances et une durabilité similaires à celles d’un système local.  Pour des conseils sur les meilleures pratiques, voir TR-4780link:https://www.netapp.com/media/17105-tr4780.pdf["Bases de données Oracle sur Microsoft Azure"^] .  Plus important encore, NetApp fournit également des kits d’outils d’automatisation qui automatisent la plupart des tâches requises pour le déploiement, la configuration, la protection des données, la migration et la gestion de votre charge de travail de base de données Oracle dans le cloud public Azure.  Les kits d'outils d'automatisation sont disponibles en téléchargement sur le site GitHub public de NetApp :link:https://github.com/NetApp-Automation/["NetApp- Automatisation"^] .
