= 
:allow-uri-read: 


. Configurer les informations d'identification.
. Créer des types d’informations d’identification. Pour les solutions impliquant ONTAP, vous devez configurer le type d'informations d'identification pour qu'il corresponde aux entrées de nom d'utilisateur et de mot de passe. Nous ajouterons également des entrées pour Cloud Central et AWS.
+
.. Accédez à Administration → Types d’informations d’identification, puis cliquez sur Ajouter.
.. Fournissez le nom et la description.
.. Collez le contenu suivant dans la configuration d'entrée :
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true
----
.. Collez le contenu suivant dans la configuration de l'injecteur et cliquez sur Enregistrer :
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
----


. Créer des informations d'identification pour ONTAP/ CVO / AWS
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation pour les informations d'identification ONTAP
.. Sélectionnez le type d’informations d’identification créé à l’étape précédente.
.. Sous Détails du type, saisissez le nom d'utilisateur et le mot de passe de vos clusters source et CVO, Cloud Central/Manager, AWS Access/Secret Key et Cloud Central Refresh Token.
.. Cliquez sur Enregistrer


. Créer des informations d'identification pour Oracle (source)
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation pour l'hôte Oracle
.. Sélectionnez le type d’informations d’identification de la machine.
.. Sous Détails du type, entrez le nom d’utilisateur et le mot de passe des hôtes Oracle.
.. Sélectionnez la méthode d’escalade des privilèges appropriée et entrez le nom d’utilisateur et le mot de passe.
.. Cliquez sur Enregistrer


. Créer des informations d'identification pour la destination Oracle
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation de l'hôte Oracle DR
.. Sélectionnez le type d’informations d’identification de la machine.
.. Sous Détails du type, entrez le nom d'utilisateur (ec2-user ou si vous l'avez modifié par défaut, entrez-le) et la clé privée SSH.
.. Sélectionnez la méthode d’escalade des privilèges appropriée (sudo) et entrez le nom d’utilisateur et le mot de passe si nécessaire.
.. Cliquez sur Enregistrer



