---
sidebar: sidebar 
permalink: mssql/sql-srv-anf-conclusion.html 
keywords: takeaways, hybrid-cloud 
summary: 'Que vous cibliez un cloud entièrement cloud ou un cloud hybride avec des bases de données extensibles, Azure NetApp Files offre d"excellentes options pour déployer et gérer les charges de travail de la base de données tout en réduisant votre coût total de possession en rendant les exigences de données transparentes pour la couche applicative.' 
---
= Conclusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Que vous cibliez un cloud entièrement cloud ou un cloud hybride avec des bases de données extensibles, Azure NetApp Files offre d'excellentes options pour déployer et gérer les charges de travail de la base de données tout en réduisant votre coût total de possession en rendant les exigences de données transparentes pour la couche applicative.

Ce document couvre les recommandations pour la planification, la conception, l’optimisation et la mise à l’échelle des déploiements Microsoft SQL Server avec Azure NetApp Files, qui peuvent varier considérablement selon les implémentations.  La solution adéquate dépend à la fois des détails techniques de la mise en œuvre et des exigences commerciales qui sous-tendent le projet.



== Plats à emporter

Les points clés de ce document comprennent :

* Vous pouvez désormais utiliser Azure NetApp Files pour héberger la base de données et le témoin de partage de fichiers pour le cluster SQL Server.
* Vous pouvez augmenter les temps de réponse des applications et fournir une disponibilité de 99,9999 % pour fournir un accès aux données SQL Server quand et où cela est nécessaire.
* Vous pouvez simplifier la complexité globale du déploiement de SQL Server et la gestion continue, comme le striping RAID, avec un redimensionnement simple et instantané.
* Vous pouvez compter sur des fonctionnalités d’opérations intelligentes pour vous aider à déployer des bases de données SQL Server en quelques minutes et à accélérer les cycles de développement.
* Si Azure Cloud est la destination, Azure NetApp Files est la solution de stockage adaptée pour un déploiement optimisé.

