---
sidebar: sidebar 
permalink: automation/awx-automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 'Cette page décrit la méthode automatisée de déploiement d"Oracle19c sur le stockage NetApp ONTAP .' 
---
= Procédure de déploiement étape par étape
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette page décrit la méthode automatisée de déploiement d'Oracle19c sur le stockage NetApp ONTAP .



== Déploiement AWX/Tower de la base de données Oracle 19c



=== 1. Créez l'inventaire, le groupe, les hôtes et les informations d'identification pour votre environnement

Cette section décrit la configuration de l'inventaire, des groupes, des hôtes et des informations d'identification d'accès dans AWX/Ansible Tower qui préparent l'environnement pour la consommation de solutions automatisées NetApp .

. Configurer l'inventaire.
+
.. Accédez à Ressources → Inventaires → Ajouter, puis cliquez sur Ajouter un inventaire.
.. Indiquez le nom et les détails de l’organisation, puis cliquez sur Enregistrer.
.. Sur la page Inventaires, cliquez sur l’inventaire créé.
.. S'il existe des variables d'inventaire, collez-les dans le champ des variables.
.. Accédez au sous-menu Groupes et cliquez sur Ajouter.
.. Indiquez le nom du groupe pour ONTAP, collez les variables du groupe (le cas échéant) et cliquez sur Enregistrer.
.. Répétez le processus pour un autre groupe pour Oracle.
.. Sélectionnez le groupe ONTAP créé, accédez au sous-menu Hôtes et cliquez sur Ajouter un nouvel hôte.
.. Fournissez l'adresse IP de l'adresse IP de gestion du cluster ONTAP , collez les variables d'hôte (le cas échéant) et cliquez sur Enregistrer.
.. Ce processus doit être répété pour le groupe Oracle et l'adresse IP/le nom d'hôte de gestion des hôtes Oracle.


. Créer des types d’informations d’identification. Pour les solutions impliquant ONTAP, vous devez configurer le type d'informations d'identification pour qu'il corresponde aux entrées de nom d'utilisateur et de mot de passe.
+
.. Accédez à Administration → Types d’informations d’identification, puis cliquez sur Ajouter.
.. Fournissez le nom et la description.
.. Collez le contenu suivant dans la configuration d'entrée :




[source, cli]
----
fields:
  - id: username
    type: string
    label: Username
  - id: password
    type: string
    label: Password
    secret: true
  - id: vsadmin_password
    type: string
    label: vsadmin_password
    secret: true
----
. Collez le contenu suivant dans la configuration de l'injecteur :


[source, cli]
----
extra_vars:
  password: '{{ password }}'
  username: '{{ username }}'
  vsadmin_password: '{{ vsadmin_password }}'
----
. Configurer les informations d'identification.
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation pour ONTAP.
.. Sélectionnez le type d’informations d’identification personnalisé que vous avez créé pour ONTAP.
.. Sous Détails du type, entrez le nom d’utilisateur, le mot de passe et le mot de passe vsadmin.
.. Cliquez sur Retour aux informations d’identification et cliquez sur Ajouter.
.. Saisissez le nom et les détails de l’organisation pour Oracle.
.. Sélectionnez le type d’informations d’identification de la machine.
.. Sous Détails du type, entrez le nom d’utilisateur et le mot de passe des hôtes Oracle.
.. Sélectionnez la méthode d’escalade des privilèges appropriée et entrez le nom d’utilisateur et le mot de passe.






=== 2. Créer un projet

. Accédez à Ressources → Projets et cliquez sur Ajouter.
+
.. Saisissez le nom et les détails de l'organisation.
.. Sélectionnez Git dans le champ Type d’informations d’identification de contrôle de source.
.. entrer `\https://github.com/NetApp-Automation/na_oracle19c_deploy.git` comme URL de contrôle de source.
.. Cliquez sur Enregistrer.
.. Le projet peut avoir besoin d'être synchronisé occasionnellement lorsque le code source change.






=== 3. Configurer Oracle host_vars

Les variables définies dans cette section sont appliquées à chaque serveur et base de données Oracle individuels.

. Saisissez vos paramètres spécifiques à l'environnement dans les variables d'hôtes Oracle intégrées suivantes ou sous la forme host_vars.



NOTE: Les éléments en bleu doivent être modifiés pour correspondre à votre environnement.



=== Configuration de l'hôte VARS

[source, shell]
----
######################################################################
##############      Host Variables Configuration        ##############
######################################################################

# Add your Oracle Host
ansible_host: "10.61.180.15"

# Oracle db log archive mode: true - ARCHIVELOG or false - NOARCHIVELOG
log_archive_mode: "true"

# Number of pluggable databases per container instance identified by sid. Pdb_name specifies the prefix for container database naming in this case cdb2_pdb1, cdb2_pdb2, cdb2_pdb3
oracle_sid: "cdb2"
pdb_num: "3"
pdb_name: "{{ oracle_sid }}_pdb"

# CDB listener port, use different listener port for additional CDB on same host
listener_port: "1523"

# CDB is created with SGA at 75% of memory_limit, MB. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB. The grand total SGA should not exceed 75% available RAM on node.
memory_limit: "5464"

# Set "em_configuration: DBEXPRESS" to install enterprise manager express and choose a unique port from 5500 to 5599 for each sid on the host.
# Leave them black if em express is not installed.
em_configuration: "DBEXPRESS"
em_express_port: "5501"

# {{groups.oracle[0]}} represents first Oracle DB server as defined in Oracle hosts group [oracle]. For concurrent multiple Oracle DB servers deployment, [0] will be incremented for each additional DB server. For example,  {{groups.oracle[1]}}" represents DB server 2, "{{groups.oracle[2]}}" represents DB server 3 ... As a good practice and the default, minimum three volumes is allocated to a DB server with corresponding /u01, /u02, /u03 mount points, which store oracle binary, oracle data, and oracle recovery files respectively. Additional volumes can be added by click on "More NFS volumes" but the number of volumes allocated to a DB server must match with what is defined in global vars file by volumes_nfs parameter, which dictates how many volumes are to be created for each DB server.
host_datastores_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
----
. Remplissez toutes les variables dans les champs bleus.
. Après avoir terminé la saisie des variables, cliquez sur le bouton Copier du formulaire pour copier toutes les variables à transférer vers AWX ou Tower.
. Revenez à AWX ou Tower et accédez à Ressources → Hôtes, puis sélectionnez et ouvrez la page de configuration du serveur Oracle.
. Sous l’onglet Détails, cliquez sur Modifier et collez les variables copiées de l’étape 1 dans le champ Variables sous l’onglet YAML.
. Cliquez sur Enregistrer.
. Répétez ce processus pour tous les serveurs Oracle supplémentaires du système.




=== 4. Configurer les variables globales

Les variables définies dans cette section s'appliquent à tous les hôtes Oracle, bases de données et au cluster ONTAP .

. Saisissez vos paramètres spécifiques à l'environnement dans les variables globales intégrées suivantes ou sous la forme de variables.



NOTE: Les éléments en bleu doivent être modifiés pour correspondre à votre environnement.

[source, shell]
----
#######################################################################
###### Oracle 19c deployment global user configuration variables ######
######  Consolidate all variables from ontap, linux and oracle   ######
#######################################################################

###########################################
### Ontap env specific config variables ###
###########################################

#Inventory group name
#Default inventory group name - 'ontap'
#Change only if you are changing the group name either in inventory/hosts file or in inventory groups in case of AWX/Tower
hosts_group: "ontap"

#CA_signed_certificates (ONLY CHANGE to 'true' IF YOU ARE USING CA SIGNED CERTIFICATES)
ca_signed_certs: "false"

#Names of the Nodes in the ONTAP Cluster
nodes:
 - "AFF-01"
 - "AFF-02"

#Storage VLANs
#Add additional rows for vlans as necessary
storage_vlans:
   - {vlan_id: "203", name: "infra_NFS", protocol: "NFS"}
More Storage VLANsEnter Storage VLANs details

#Details of the Data Aggregates that need to be created
#If Aggregate creation takes longer, subsequent tasks of creating volumes may fail.
#There should be enough disks already zeroed in the cluster, otherwise aggregate create will zero the disks and will take long time
data_aggregates:
  - {aggr_name: "aggr01_node01"}
  - {aggr_name: "aggr01_node02"}

#SVM name
svm_name: "ora_svm"

# SVM Management LIF Details
svm_mgmt_details:
  - {address: "172.21.91.100", netmask: "255.255.255.0", home_port: "e0M"}

# NFS storage parameters when data_protocol set to NFS. Volume named after Oracle hosts name identified by mount point as follow for oracle DB server 1. Each mount point dedicates to a particular Oracle files: u01 - Oracle binary, u02 - Oracle data, u03 - Oracle redo. Add additional volumes by click on "More NFS volumes" and also add the volumes list to corresponding host_vars as host_datastores_nfs variable. For multiple DB server deployment, additional volumes sets needs to be added for additional DB server. Input variable "{{groups.oracle[1]}}_u01", "{{groups.oracle[1]}}_u02", and "{{groups.oracle[1]}}_u03" as vol_name for second DB server. Place volumes for multiple DB servers alternatingly between controllers for balanced IO performance, e.g. DB server 1 on controller node1, DB server 2 on controller node2 etc. Make sure match lif address with controller node.

volumes_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}

#NFS LIFs IP address and netmask

nfs_lifs_details:
  - address: "172.21.94.200" #for node-1
    netmask: "255.255.255.0"
  - address: "172.21.94.201" #for node-2
    netmask: "255.255.255.0"

#NFS client match

client_match: "172.21.94.0/24"

###########################################
### Linux env specific config variables ###
###########################################

#NFS Mount points for Oracle DB volumes

mount_points:
  - "/u01"
  - "/u02"
  - "/u03"

# Up to 75% of node memory size divided by 2mb. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB.
# Leave it blank if hugepage is not configured on the host.

hugepages_nr: "1234"

# RedHat subscription username and password

redhat_sub_username: "xxx"
redhat_sub_password: "xxx"

####################################################
### DB env specific install and config variables ###
####################################################

db_domain: "your.domain.com"

# Set initial password for all required Oracle passwords. Change them after installation.

initial_pwd_all: "netapp123"
----
. Remplissez toutes les variables dans les champs bleus.
. Après avoir terminé la saisie des variables, cliquez sur le bouton Copier du formulaire pour copier toutes les variables à transférer vers AWX ou Tower dans le modèle de travail suivant.




=== 5. Configurer et lancer le modèle de travail.

. Créez le modèle de travail.
+
.. Accédez à Ressources → Modèles → Ajouter et cliquez sur Ajouter un modèle de travail.
.. Entrez le nom et la description
.. Sélectionnez le type de travail ; Exécuter configure le système en fonction d'un playbook et Vérifier effectue une exécution à sec d'un playbook sans réellement configurer le système.
.. Sélectionnez l’inventaire, le projet, le playbook et les informations d’identification correspondants pour le playbook.
.. Sélectionnez all_playbook.yml comme playbook par défaut à exécuter.
.. Collez les variables globales copiées à l’étape 4 dans le champ Variables de modèle sous l’onglet YAML.
.. Cochez la case Invite au lancement dans le champ Balises de tâche.
.. Cliquez sur Enregistrer.


. Lancez le modèle de travail.
+
.. Accédez à Ressources → Modèles.
.. Cliquez sur le modèle souhaité, puis sur Lancer.
.. Lorsque vous êtes invité au lancement pour les balises de travail, saisissez requirements_config.  Vous devrez peut-être cliquer sur la ligne Créer une balise de travail sous requirements_config pour saisir la balise de travail.





NOTE: requirements_config garantit que vous disposez des bibliothèques appropriées pour exécuter les autres rôles.

. Cliquez sur Suivant, puis sur Lancer pour démarrer le travail.
. Cliquez sur Affichage → Tâches pour surveiller la sortie et la progression des tâches.
. Lorsque vous êtes invité au lancement pour les balises de travail, saisissez ontap_config.  Vous devrez peut-être cliquer sur la ligne Créer « Balise de travail » juste en dessous de ontap_config pour saisir la balise de travail.
. Cliquez sur Suivant, puis sur Lancer pour démarrer le travail.
. Cliquez sur Affichage → Tâches pour surveiller la sortie et la progression des tâches
. Une fois le rôle ontap_config terminé, exécutez à nouveau le processus pour linux_config.
. Accédez à Ressources → Modèles.
. Sélectionnez le modèle souhaité, puis cliquez sur Lancer.
. Lorsque vous êtes invité au lancement à saisir les balises de travail dans linux_config, vous devrez peut-être sélectionner la ligne Créer « balise de travail » juste en dessous de linux_config pour saisir la balise de travail.
. Cliquez sur Suivant, puis sur Lancer pour démarrer le travail.
. Sélectionnez Affichage → Tâches pour surveiller la sortie et la progression des tâches.
. Une fois le rôle linux_config terminé, exécutez à nouveau le processus pour oracle_config.
. Accédez à Ressources → Modèles.
. Sélectionnez le modèle souhaité, puis cliquez sur Lancer.
. Lorsque vous êtes invité au lancement pour les balises de travail, saisissez oracle_config.  Vous devrez peut-être sélectionner la ligne Créer « Balise de travail » juste en dessous de oracle_config pour saisir la balise de travail.
. Cliquez sur Suivant, puis sur Lancer pour démarrer le travail.
. Sélectionnez Affichage → Tâches pour surveiller la sortie et la progression des tâches.




=== 6. Déployer une base de données supplémentaire sur le même hôte Oracle

La partie Oracle du playbook crée une seule base de données de conteneur Oracle sur un serveur Oracle par exécution.  Pour créer des bases de données de conteneurs supplémentaires sur le même serveur, procédez comme suit.

. Réviser les variables host_vars.
+
.. Revenez à l’étape 2 – Configurer Oracle host_vars.
.. Modifiez le SID Oracle en une chaîne de dénomination différente.
.. Modifiez le port d'écoute sur un numéro différent.
.. Modifiez le port EM Express sur un numéro différent si vous installez EM Express.
.. Copiez et collez les variables d’hôte révisées dans le champ Variables d’hôte Oracle dans l’onglet Détails de la configuration de l’hôte.


. Lancez le modèle de tâche de déploiement avec uniquement la balise oracle_config.
. Connectez-vous au serveur Oracle en tant qu’utilisateur Oracle et exécutez les commandes suivantes :
+
[source, cli]
----
ps -ef | grep ora
----
+

NOTE: Cela répertoriera les processus Oracle si l'installation s'est terminée comme prévu et que la base de données Oracle a démarré.

. Connectez-vous à la base de données pour vérifier les paramètres de configuration de la base de données et les PDB créés avec les ensembles de commandes suivants.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus / as sysdba

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 12:52:51 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL>

SQL> select name, log_mode from v$database;
NAME      LOG_MODE
--------- ------------
CDB2      ARCHIVELOG

SQL> show pdbs

    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO

col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;

SQL> col svrname form a30
SQL> col dirname form a30
SQL> select svrname, dirname, nfsversion from v$dnfs_servers;

SVRNAME                        DIRNAME                        NFSVERSION
------------------------------ ------------------------------ ----------------
172.21.126.200                 /rhelora03_u02                 NFSv3.0
172.21.126.200                 /rhelora03_u03                 NFSv3.0
172.21.126.200                 /rhelora03_u01                 NFSv3.0
----
+
Cela confirme que dNFS fonctionne correctement.

. Connectez-vous à la base de données via l'écouteur pour vérifier la configuration de l'écouteur Oracle avec la commande suivante.  Passez au port d'écoute et au nom du service de base de données appropriés.
+
[source, cli]
----
[oracle@localhost ~]$ sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com

SQL*Plus: Release 19.0.0.0.0 - Production on Thu May 6 13:19:57 2021
Version 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Wed May 05 2021 17:11:11 -04:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.8.0.0.0

SQL> show user
USER is "SYSTEM"
SQL> show con_name
CON_NAME
CDB2_PDB1
----
+
Cela confirme que l'écouteur Oracle fonctionne correctement.





=== Où aller chercher de l’aide ?

Si vous avez besoin d'aide avec la boîte à outils, veuillez vous joindre à nous.link:https://netapppub.slack.com/archives/C021R4WC0LC["Canal Slack d'assistance de la communauté NetApp Solution Automation"] et recherchez le canal solution-automatisation pour poster vos questions ou demandes de renseignements.
