---
sidebar: sidebar 
permalink: automation/db-protection-awx-automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 'Cette page décrit la protection automatisée des données d"Oracle19c sur le stockage NetApp ONTAP .' 
---
= Procédure de déploiement étape par étape
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette page décrit la protection automatisée des données d'Oracle19c sur le stockage NetApp ONTAP .



== Protection des données Oracle AWX/Tower



=== Créez l'inventaire, le groupe, les hôtes et les informations d'identification pour votre environnement

Cette section décrit la configuration de l'inventaire, des groupes, des hôtes et des informations d'identification d'accès dans AWX/Ansible Tower qui préparent l'environnement pour la consommation de solutions automatisées NetApp .

. Configurer l'inventaire.
+
.. Accédez à Ressources → Inventaires → Ajouter, puis cliquez sur Ajouter un inventaire.
.. Indiquez le nom et les détails de l’organisation, puis cliquez sur Enregistrer.
.. Sur la page Inventaires, cliquez sur l’inventaire créé.
.. Accédez au sous-menu Groupes et cliquez sur Ajouter.
.. Indiquez le nom Oracle de votre premier groupe et cliquez sur Enregistrer.
.. Répétez le processus pour un deuxième groupe appelé dr_oracle.
.. Sélectionnez le groupe Oracle créé, accédez au sous-menu Hôtes et cliquez sur Ajouter un nouvel hôte.
.. Fournissez l'adresse IP de l'adresse IP de gestion de l'hôte Oracle source, puis cliquez sur Enregistrer.
.. Ce processus doit être répété pour le groupe dr_oracle et ajouter l'adresse IP/le nom d'hôte de gestion de l'hôte Oracle DR/Destination.





NOTE: Vous trouverez ci-dessous des instructions pour créer les types d'informations d'identification et les informations d'identification pour On-Prem avec ONTAP ou CVO sur AWS.

[role="tabbed-block"]
====
.Sur site
--
. Configurer les informations d'identification.
. Créer des types d’informations d’identification.  Pour les solutions impliquant ONTAP, vous devez configurer le type d'informations d'identification pour qu'il corresponde aux entrées de nom d'utilisateur et de mot de passe.
+
.. Accédez à Administration → Types d’informations d’identification, puis cliquez sur Ajouter.
.. Fournissez le nom et la description.
.. Collez le contenu suivant dans la configuration d'entrée :
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: Destination Cluster Username
  - id: dst_cluster_password
    type: string
    label: Destination Cluster Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
----
.. Collez le contenu suivant dans la configuration de l'injecteur, puis cliquez sur Enregistrer :
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
----


. Créer des informations d'identification pour ONTAP
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation pour les informations d'identification ONTAP
.. Sélectionnez le type d’informations d’identification créé à l’étape précédente.
.. Sous Détails du type, saisissez le nom d’utilisateur et le mot de passe de vos clusters source et de destination.
.. Cliquez sur Enregistrer


. Créer des informations d'identification pour Oracle
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation pour Oracle
.. Sélectionnez le type d’informations d’identification de la machine.
.. Sous Détails du type, entrez le nom d’utilisateur et le mot de passe des hôtes Oracle.
.. Sélectionnez la méthode d’escalade des privilèges appropriée et entrez le nom d’utilisateur et le mot de passe.
.. Cliquez sur Enregistrer
.. Répétez le processus si nécessaire pour des informations d'identification différentes pour l'hôte dr_oracle.




--
.CVO
--
. Configurer les informations d'identification.
. Créer des types d’informations d’identification. Pour les solutions impliquant ONTAP, vous devez configurer le type d'informations d'identification pour qu'il corresponde aux entrées de nom d'utilisateur et de mot de passe. Nous ajouterons également des entrées pour Cloud Central et AWS.
+
.. Accédez à Administration → Types d’informations d’identification, puis cliquez sur Ajouter.
.. Fournissez le nom et la description.
.. Collez le contenu suivant dans la configuration d'entrée :
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true
----
.. Collez le contenu suivant dans la configuration de l'injecteur et cliquez sur Enregistrer :
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
----


. Créer des informations d'identification pour ONTAP/ CVO / AWS
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation pour les informations d'identification ONTAP
.. Sélectionnez le type d’informations d’identification créé à l’étape précédente.
.. Sous Détails du type, saisissez le nom d'utilisateur et le mot de passe de vos clusters source et CVO, Cloud Central/Manager, AWS Access/Secret Key et Cloud Central Refresh Token.
.. Cliquez sur Enregistrer


. Créer des informations d'identification pour Oracle (source)
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation pour l'hôte Oracle
.. Sélectionnez le type d’informations d’identification de la machine.
.. Sous Détails du type, entrez le nom d’utilisateur et le mot de passe des hôtes Oracle.
.. Sélectionnez la méthode d’escalade des privilèges appropriée et entrez le nom d’utilisateur et le mot de passe.
.. Cliquez sur Enregistrer


. Créer des informations d'identification pour la destination Oracle
+
.. Accédez à Ressources → Informations d’identification, puis cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation de l'hôte Oracle DR
.. Sélectionnez le type d’informations d’identification de la machine.
.. Sous Détails du type, entrez le nom d'utilisateur (ec2-user ou si vous l'avez modifié par défaut, entrez-le) et la clé privée SSH.
.. Sélectionnez la méthode d’escalade des privilèges appropriée (sudo) et entrez le nom d’utilisateur et le mot de passe si nécessaire.
.. Cliquez sur Enregistrer




--
====


=== Créer un projet

. Accédez à Ressources → Projets et cliquez sur Ajouter.
+
.. Saisissez le nom et les détails de l'organisation.
.. Sélectionnez Git dans le champ Type d’informations d’identification de contrôle de source.
.. entrer `\https://github.com/NetApp-Automation/na_oracle19c_data_protection.git` comme URL de contrôle de source.
.. Cliquez sur Enregistrer.
.. Le projet peut avoir besoin d'être synchronisé occasionnellement lorsque le code source change.






=== Configurer les variables globales

Les variables définies dans cette section s'appliquent à tous les hôtes Oracle, bases de données et au cluster ONTAP .

. Saisissez vos paramètres spécifiques à l'environnement dans les variables globales intégrées suivantes ou sous la forme de variables.



NOTE: Les éléments en bleu doivent être modifiés pour correspondre à votre environnement.

[role="tabbed-block"]
====
.Sur site
--
[source, shell]
----
# Oracle Data Protection global user configuration variables
# Ontap env specific config variables
hosts_group: "ontap"
ca_signed_certs: "false"

# Inter-cluster LIF details
src_nodes:
  - "AFF-01"
  - "AFF-02"

dst_nodes:
  - "DR-AFF-01"
  - "DR-AFF-02"

create_source_intercluster_lifs: "yes"

source_intercluster_network_port_details:
  using_dedicated_ports: "yes"
  using_ifgrp: "yes"
  using_vlans: "yes"
  failover_for_shared_individual_ports: "yes"
  ifgrp_name: "a0a"
  vlan_id: "10"
  ports:
    - "e0b"
    - "e0g"
  broadcast_domain: "NFS"
  ipspace: "Default"
  failover_group_name: "iclifs"

source_intercluster_lif_details:
  - name: "icl_1"
    address: "10.0.0.1"
    netmask: "255.255.255.0"
    home_port: "a0a-10"
    node: "AFF-01"
  - name: "icl_2"
    address: "10.0.0.2"
    netmask: "255.255.255.0"
    home_port: "a0a-10"
    node: "AFF-02"

create_destination_intercluster_lifs: "yes"

destination_intercluster_network_port_details:
  using_dedicated_ports: "yes"
  using_ifgrp: "yes"
  using_vlans: "yes"
  failover_for_shared_individual_ports: "yes"
  ifgrp_name: "a0a"
  vlan_id: "10"
  ports:
    - "e0b"
    - "e0g"
  broadcast_domain: "NFS"
  ipspace: "Default"
  failover_group_name: "iclifs"

destination_intercluster_lif_details:
  - name: "icl_1"
    address: "10.0.0.3"
    netmask: "255.255.255.0"
    home_port: "a0a-10"
    node: "DR-AFF-01"
  - name: "icl_2"
    address: "10.0.0.4"
    netmask: "255.255.255.0"
    home_port: "a0a-10"
    node: "DR-AFF-02"

# Variables for SnapMirror Peering
passphrase: "your-passphrase"

# Source & Destination List
dst_cluster_name: "dst-cluster-name"
dst_cluster_ip: "dst-cluster-ip"
dst_vserver: "dst-vserver"
dst_nfs_lif: "dst-nfs-lif"
src_cluster_name: "src-cluster-name"
src_cluster_ip: "src-cluster-ip"
src_vserver: "src-vserver"

# Variable for Oracle Volumes and SnapMirror Details
cg_snapshot_name_prefix: "oracle"
src_orabinary_vols:
  - "binary_vol"
src_db_vols:
  - "db_vol"
src_archivelog_vols:
  - "log_vol"
snapmirror_policy: "async_policy_oracle"

# Export Policy Details
export_policy_details:
  name: "nfs_export_policy"
  client_match: "0.0.0.0/0"
  ro_rule: "sys"
  rw_rule: "sys"

# Linux env specific config variables
mount_points:
  - "/u01"
  - "/u02"
  - "/u03"
hugepages_nr: "1234"
redhat_sub_username: "xxx"
redhat_sub_password: "xxx"

# DB env specific install and config variables
recovery_type: "scn"
control_files:
  - "/u02/oradata/CDB2/control01.ctl"
  - "/u03/orareco/CDB2/control02.ctl"
----
--
.CVO
--
[source, shell]
----
###########################################
### Ontap env specific config variables ###
###########################################

#Inventory group name
#Default inventory group name - "ontap"
#Change only if you are changing the group name either in inventory/hosts file or in inventory groups in case of AWX/Tower
hosts_group: "ontap"

#CA_signed_certificates (ONLY CHANGE to "true" IF YOU ARE USING CA SIGNED CERTIFICATES)
ca_signed_certs: "false"

#Names of the Nodes in the Source ONTAP Cluster
src_nodes:
  - "AFF-01"
  - "AFF-02"

#Names of the Nodes in the Destination CVO Cluster
dst_nodes:
  - "DR-AFF-01"
  - "DR-AFF-02"

#Define whether or not to create intercluster lifs on source cluster (ONLY CHANGE to "No" IF YOU HAVE ALREADY CREATED THE INTERCLUSTER LIFS)
create_source_intercluster_lifs: "yes"

source_intercluster_network_port_details:
  using_dedicated_ports: "yes"
  using_ifgrp: "yes"
  using_vlans: "yes"
  failover_for_shared_individual_ports: "yes"
  ifgrp_name: "a0a"
  vlan_id: "10"
  ports:
    - "e0b"
    - "e0g"
  broadcast_domain: "NFS"
  ipspace: "Default"
  failover_group_name: "iclifs"

source_intercluster_lif_details:
  - name: "icl_1"
    address: "10.0.0.1"
    netmask: "255.255.255.0"
    home_port: "a0a-10"
    node: "AFF-01"
  - name: "icl_2"
    address: "10.0.0.2"
    netmask: "255.255.255.0"
    home_port: "a0a-10"
    node: "AFF-02"

###########################################
### CVO Deployment Variables ###
###########################################

####### Access Keys Variables ######

# Region where your CVO will be deployed.
region_deploy: "us-east-1"

########### CVO and Connector Vars ########

# AWS Managed Policy required to give permission for IAM role creation.
aws_policy: "arn:aws:iam::1234567:policy/OCCM"

# Specify your aws role name, a new role is created if one already does not exist.
aws_role_name: "arn:aws:iam::1234567:policy/OCCM"

# Name your connector.
connector_name: "awx_connector"

# Name of the key pair generated in AWS.
key_pair: "key_pair"

# Name of the Subnet that has the range of IP addresses in your VPC.
subnet: "subnet-12345"

# ID of your AWS secuirty group that allows access to on-prem resources.
security_group: "sg-123123123"

# You Cloud Manager Account ID.
account: "account-A23123A"

# Name of the your CVO instance
cvo_name: "test_cvo"

# ID of the VPC in AWS.
vpc: "vpc-123123123"

###################################################################################################
# Variables for - Add on-prem ONTAP to Connector in Cloud Manager
###################################################################################################

# For Federated users, Client ID from API Authentication Section of Cloud Central to generate access token.
sso_id: "123123123123123123123"

# For regular access with username and password, please specify "pass" as the connector_access. For SSO users, use "refresh_token" as the variable.
connector_access: "pass"

####################################################################################################
# Variables for SnapMirror Peering
####################################################################################################
passphrase: "your-passphrase"

#####################################################################################################
# Source & Destination List
#####################################################################################################
#Please Enter Destination Cluster Name
dst_cluster_name: "dst-cluster-name"

#Please Enter Destination Cluster (Once CVO is Created Add this Variable to all templates)
dst_cluster_ip: "dst-cluster-ip"

#Please Enter Destination SVM to create mirror relationship
dst_vserver: "dst-vserver"

#Please Enter NFS Lif for dst vserver (Once CVO is Created Add this Variable to all templates)
dst_nfs_lif: "dst-nfs-lif"

#Please Enter Source Cluster Name
src_cluster_name: "src-cluster-name"

#Please Enter Source Cluster
src_cluster_ip: "src-cluster-ip"

#Please Enter Source SVM
src_vserver: "src-vserver"

#####################################################################################################
# Variable for Oracle Volumes and SnapMirror Details
#####################################################################################################
#Please Enter Source Snapshot Prefix Name
cg_snapshot_name_prefix: "oracle"

#Please Enter Source Oracle Binary Volume(s)
src_orabinary_vols:
  - "binary_vol"
#Please Enter Source Database Volume(s)
src_db_vols:
  - "db_vol"
#Please Enter Source Archive Volume(s)
src_archivelog_vols:
  - "log_vol"
#Please Enter Destination Snapmirror Policy
snapmirror_policy: "async_policy_oracle"

#####################################################################################################
# Export Policy Details
#####################################################################################################
#Enter the destination export policy details (Once CVO is Created Add this Variable to all templates)
export_policy_details:
  name: "nfs_export_policy"
  client_match: "0.0.0.0/0"
  ro_rule: "sys"
  rw_rule: "sys"

#####################################################################################################
### Linux env specific config variables ###
#####################################################################################################

#NFS Mount points for Oracle DB volumes
mount_points:
  - "/u01"
  - "/u02"
  - "/u03"

# Up to 75% of node memory size divided by 2mb. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB.
# Leave it blank if hugepage is not configured on the host.
hugepages_nr: "1234"

# RedHat subscription username and password
redhat_sub_username: "xxx"
redhat_sub_password: "xxx"

####################################################
### DB env specific install and config variables ###
####################################################
#Recovery Type (leave as scn)
recovery_type: "scn"

#Oracle Control Files
control_files:
  - "/u02/oradata/CDB2/control01.ctl"
  - "/u03/orareco/CDB2/control02.ctl"
----
--
====


=== Manuels d'automatisation

Il y a quatre manuels de jeu distincts qui doivent être exécutés.

. Manuel de configuration de votre environnement, sur site ou CVO.
. Manuel de réplication des binaires et des bases de données Oracle selon un calendrier
. Manuel de réplication des journaux Oracle selon un calendrier
. Manuel de récupération de votre base de données sur un hôte de destination


[role="tabbed-block"]
====
.Configuration ONTAP/ CVO
--
[.underline]* Configuration ONTAP et CVO*

*Configurer et lancer le modèle de tâche.*

. Créez le modèle de travail.
+
.. Accédez à Ressources → Modèles → Ajouter et cliquez sur Ajouter un modèle de travail.
.. Entrez le nom ONTAP/CVO Setup
.. Sélectionnez le type de travail ; Exécuter configure le système en fonction d'un playbook.
.. Sélectionnez l’inventaire, le projet, le playbook et les informations d’identification correspondants pour le playbook.
.. Sélectionnez le playbook ontap_setup.yml pour un environnement sur site ou sélectionnez cvo_setup.yml pour la réplication vers une instance CVO.
.. Collez les variables globales copiées à l’étape 4 dans le champ Variables de modèle sous l’onglet YAML.
.. Cliquez sur Enregistrer.


. Lancez le modèle de travail.
+
.. Accédez à Ressources → Modèles.
.. Cliquez sur le modèle souhaité, puis sur Lancer.
+

NOTE: Nous utiliserons ce modèle et le copierons pour les autres playbooks.





--
.Réplication pour les volumes binaires et de base de données
--
[.underline]*Planification du manuel de réplication binaire et de base de données*

*Configurer et lancer le modèle de tâche.*

. Copiez le modèle de travail précédemment créé.
+
.. Accédez à Ressources → Modèles.
.. Recherchez le modèle de configuration ONTAP/ CVO et, à l'extrême droite, cliquez sur Copier le modèle
.. Cliquez sur Modifier le modèle sur le modèle copié et remplacez le nom par Playbook de réplication binaire et de base de données.
.. Conservez le même inventaire, le même projet et les mêmes informations d'identification pour le modèle.
.. Sélectionnez ora_replication_cg.yml comme playbook à exécuter.
.. Les variables resteront les mêmes, mais l'adresse IP du cluster CVO devra être définie dans la variable dst_cluster_ip.
.. Cliquez sur Enregistrer.


. Planifiez le modèle de travail.
+
.. Accédez à Ressources → Modèles.
.. Cliquez sur le modèle Playbook de réplication binaire et de base de données, puis cliquez sur Planifications dans l’ensemble d’options supérieur.
.. Cliquez sur Ajouter, ajoutez le nom de la planification pour la réplication binaire et de base de données, choisissez la date/heure de début au début de l'heure, choisissez votre fuseau horaire local et la fréquence d'exécution.  La fréquence d'exécution sera souvent celle à laquelle la réplication SnapMirror sera mise à jour.
+

NOTE: Un calendrier distinct sera créé pour la réplication du volume de journaux, afin qu'il puisse être répliqué à une cadence plus fréquente.





--
.Réplication des volumes de journaux
--
[.underline]*Planification du manuel de réplication des journaux*

*Configurer et lancer le modèle de tâche*

. Copiez le modèle de travail précédemment créé.
+
.. Accédez à Ressources → Modèles.
.. Recherchez le modèle de configuration ONTAP/ CVO et, à l'extrême droite, cliquez sur Copier le modèle
.. Cliquez sur Modifier le modèle sur le modèle copié et remplacez le nom par Playbook de réplication de journaux.
.. Conservez le même inventaire, le même projet et les mêmes informations d'identification pour le modèle.
.. Sélectionnez ora_replication_logs.yml comme playbook à exécuter.
.. Les variables resteront les mêmes, mais l'adresse IP du cluster CVO devra être définie dans la variable dst_cluster_ip.
.. Cliquez sur Enregistrer.


. Planifiez le modèle de travail.
+
.. Accédez à Ressources → Modèles.
.. Cliquez sur le modèle Playbook de réplication des journaux, puis sur Planifications dans l’ensemble d’options supérieur.
.. Cliquez sur Ajouter, ajoutez le nom de la planification pour la réplication du journal, choisissez la date/heure de début au début de l'heure, choisissez votre fuseau horaire local et la fréquence d'exécution.  La fréquence d'exécution sera souvent celle à laquelle la réplication SnapMirror sera mise à jour.


+

NOTE: Il est recommandé de définir la planification du journal pour qu'il soit mis à jour toutes les heures afin de garantir la récupération jusqu'à la dernière mise à jour horaire.



--
.Restaurer et récupérer la base de données
--
[.underline]*Planification du manuel de réplication des journaux*

*Configurer et lancer le modèle de tâche.*

. Copiez le modèle de travail précédemment créé.
+
.. Accédez à Ressources → Modèles.
.. Recherchez le modèle de configuration ONTAP/ CVO et, à l'extrême droite, cliquez sur Copier le modèle
.. Cliquez sur Modifier le modèle sur le modèle copié et remplacez le nom par Playbook de restauration et de récupération.
.. Conservez le même inventaire, le même projet et les mêmes informations d'identification pour le modèle.
.. Sélectionnez ora_recovery.yml comme playbook à exécuter.
.. Les variables resteront les mêmes, mais l'adresse IP du cluster CVO devra être définie dans la variable dst_cluster_ip.
.. Cliquez sur Enregistrer.


+

NOTE: Ce playbook ne sera pas exécuté tant que vous ne serez pas prêt à restaurer votre base de données sur le site distant.



--
====


=== Récupération de la base de données Oracle

. Les volumes de données des bases de données Oracle de production sur site sont protégés via la réplication NetApp SnapMirror vers un cluster ONTAP redondant dans un centre de données secondaire ou vers Cloud Volume ONTAP dans un cloud public.  Dans un environnement de reprise après sinistre entièrement configuré, les instances de calcul de récupération dans un centre de données secondaire ou un cloud public sont en veille et prêtes à récupérer la base de données de production en cas de sinistre.  Les instances de calcul de secours sont maintenues synchronisées avec les instances sur site en exécutant des mises à jour parallèles sur le correctif ou la mise à niveau du noyau du système d'exploitation en mode verrouillé.
. Dans cette solution démontrée, le volume binaire Oracle est répliqué sur la cible et monté sur l'instance cible pour faire apparaître la pile logicielle Oracle.  Cette approche pour récupérer Oracle présente un avantage par rapport à une nouvelle installation d’Oracle à la dernière minute lorsqu’un sinistre survient.  Il garantit que l'installation d'Oracle est entièrement synchronisée avec l'installation actuelle du logiciel de production sur site et les niveaux de correctifs, etc. Cependant, cela peut ou non avoir des implications supplémentaires en matière de licence logicielle pour le volume binaire Oracle répliqué sur le site de récupération, en fonction de la manière dont la licence logicielle est structurée avec Oracle.  Il est recommandé à l'utilisateur de vérifier auprès de son personnel chargé des licences logicielles afin d'évaluer les exigences potentielles en matière de licences Oracle avant de décider d'utiliser la même approche.
. L'hôte Oracle de secours à la destination est configuré avec les configurations prérequises Oracle.
. Les SnapMirrors sont cassés et les volumes sont rendus accessibles en écriture et montés sur l'hôte Oracle de secours.
. Le module de récupération Oracle exécute les tâches suivantes pour récupérer et démarrer Oracle sur le site de récupération une fois que tous les volumes de base de données sont montés sur l'instance de calcul de secours.
+
.. Synchroniser le fichier de contrôle : nous avons déployé des fichiers de contrôle Oracle en double sur différents volumes de base de données pour protéger le fichier de contrôle de base de données critique.  L'un concerne le volume de données et l'autre le volume de journaux.  Étant donné que les volumes de données et de journaux sont répliqués à des fréquences différentes, ils ne seront pas synchronisés au moment de la récupération.
.. Relier le binaire Oracle : étant donné que le binaire Oracle est déplacé vers un nouvel hôte, il a besoin d'une nouvelle liaison.
.. Récupérer la base de données Oracle : le mécanisme de récupération récupère le dernier numéro de modification du système dans le dernier journal archivé disponible dans le volume de journal Oracle à partir du fichier de contrôle et récupère la base de données Oracle pour récupérer toutes les transactions commerciales qui ont pu être répliquées sur le site DR au moment de la panne.  La base de données est ensuite démarrée dans une nouvelle incarnation pour effectuer les connexions utilisateur et les transactions commerciales sur le site de récupération.





NOTE: Avant d'exécuter le playbook de récupération, assurez-vous de disposer des éléments suivants : Assurez-vous de copier les fichiers /etc/oratab et /etc/oraInst.loc de l'hôte Oracle source vers l'hôte de destination.
