---
sidebar: sidebar 
permalink: automation/db-protection-getting-started.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 'Cette page décrit la méthode automatisée de déploiement d"Oracle Data Protection sur le stockage NetApp ONTAP .' 
---
= Commencer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette solution a été conçue pour être exécutée dans un environnement AWX/Tower.



== AWX/Tour

Pour les environnements AWX/Tower, vous êtes guidé dans la création d'un inventaire de votre gestion de cluster ONTAP et de votre serveur Oracle (adresses IP et noms d'hôte), la création d'informations d'identification, la configuration d'un projet qui extrait le code Ansible de NetApp Automation Github et le modèle de travail qui lance l'automatisation.

. La solution a été conçue pour fonctionner dans un scénario de cloud privé (sur site vers sur site) et de cloud hybride (sur site vers cloud public Cloud Volumes ONTAP [CVO])
. Remplissez les variables spécifiques à votre environnement, puis copiez-collez-les dans les champs Variables supplémentaires de votre modèle de travail.
. Une fois les variables supplémentaires ajoutées à votre modèle de travail, vous pouvez lancer l'automatisation.
. L'automatisation est configurée pour être exécutée en trois phases (configuration, planification de réplication pour les binaires Oracle, base de données, journaux et planification de réplication uniquement pour les journaux) et une quatrième phase pour récupérer la base de données sur un site DR.
. Pour obtenir des instructions détaillées sur l'obtention des clés et des jetons nécessaires à la protection des données CVO, visitezlink:https://docs.netapp.com/us-en/netapp-solutions-dataops/automation/authentication-tokens.html["Rassembler les prérequis pour les déploiements CVO et Connector"^]




== Exigences

[role="tabbed-block"]
====
.<strong class="big">Sur site</strong>
--
[cols="3, 9"]
|===
| Environnement | Exigences 


.4+| *Environnement Ansible* | AWX/Tour 


| Ansible v.2.10 et supérieur 


| Python 3 


| Bibliothèques Python - netapp-lib - xmltodict - jmespath 


.3+| * ONTAP* | ONTAP version 9.8 + 


| Deux agrégats de données 


| NFS vlan et ifgrp créés 


.5+| *Serveur(s) Oracle* | RHEL 7/8 


| Oracle Linux 7/8 


| Interfaces réseau pour NFS, gestion publique et facultative 


| Environnement Oracle existant sur la source et système d'exploitation Linux équivalent sur la destination (site DR ou cloud public) 
|===
--
.<strong class="big">CVO</strong>
--
[cols="3, 9"]
|===
| Environnement | Exigences 


.4+| *Environnement Ansible* | AWX/Tour 


| Ansible v.2.10 et supérieur 


| Python 3 


| Bibliothèques Python - netapp-lib - xmltodict - jmespath 


.3+| * ONTAP* | ONTAP version 9.8 + 


| Deux agrégats de données 


| NFS vlan et ifgrp créés 


.5+| *Serveur(s) Oracle* | RHEL 7/8 


| Oracle Linux 7/8 


| Interfaces réseau pour NFS, gestion publique et facultative 


| Environnement Oracle existant sur la source et système d'exploitation Linux équivalent sur la destination (site DR ou cloud public) 


| Définissez un espace de swap approprié sur l'instance Oracle EC2. Par défaut, certaines instances EC2 sont déployées avec 0 swap. 


.4+| *Gestionnaire de cloud/AWS* | Accès AWS/Clé secrète 


| Compte NetApp Cloud Manager 


| Jeton d'actualisation de NetApp Cloud Manager 


| Ajouter des LIF intercluster source au groupe de sécurité AWS 
|===
--
====


== Détails de l'automatisation

[role="tabbed-block"]
====
.<strong class="big">Sur site</strong>
--
Ce déploiement automatisé est conçu avec un seul playbook Ansible composé de trois rôles distincts.  Les rôles sont destinés aux configurations ONTAP, Linux et Oracle.  Le tableau suivant décrit les tâches qui sont automatisées.

[cols="3, 9"]
|===
| Manuel de jeu | Tâches 


.5+| *ontap_setup* | Pré-vérification de l'environnement ONTAP 


| Création de LIF intercluster sur le cluster source (FACULTATIF) 


| Création de LIF intercluster sur le cluster de destination (FACULTATIF) 


| Création de cluster et peering SVM 


| Création du SnapMirror de destination et initialisation des volumes Oracle désignés 


.4+| *ora_replication_cg* | Activer le mode de sauvegarde pour chaque base de données dans /etc/oratab 


| Capture instantanée des volumes binaires et de base de données Oracle 


| Snapmirror mis à jour 


| Désactiver le mode de sauvegarde pour chaque base de données dans /etc/oratab 


.3+| *ora_replication_log* | Changer le journal actuel pour chaque base de données dans /etc/oratab 


| Instantané pris du volume du journal Oracle 


| Snapmirror mis à jour 


.5+| *ora_recovery* | Briser SnapMirror 


| Activer NFS et créer un chemin de jonction pour les volumes Oracle sur la destination 


| Configurer l'hôte Oracle DR 


| Monter et vérifier les volumes Oracle 


| Récupérer et démarrer la base de données Oracle 
|===
--
.<strong class="big">CVO</strong>
--
Ce déploiement automatisé est conçu avec un seul playbook Ansible composé de trois rôles distincts.  Les rôles sont destinés aux configurations ONTAP, Linux et Oracle.  Le tableau suivant décrit les tâches qui sont automatisées.

[cols="4, 9"]
|===
| Manuel de jeu | Tâches 


.7+| *cvo_setup* | Pré-vérification de l'environnement 


| Configuration AWS/ID de clé d'accès AWS/Clé secrète/Région par défaut 


| Création d'un rôle AWS 


| Création d'une instance NetApp Cloud Manager Connector dans AWS 


| Création d'une instance Cloud Volumes ONTAP (CVO) dans AWS 


| Ajouter un cluster ONTAP source sur site à NetApp Cloud Manager 


| Création du SnapMirror de destination et initialisation des volumes Oracle désignés 


.4+| *ora_replication_cg* | Activer le mode de sauvegarde pour chaque base de données dans /etc/oratab 


| Capture instantanée des volumes binaires et de base de données Oracle 


| Snapmirror mis à jour 


| Désactiver le mode de sauvegarde pour chaque base de données dans /etc/oratab 


.3+| *ora_replication_log* | Changer le journal actuel pour chaque base de données dans /etc/oratab 


| Instantané pris du volume du journal Oracle 


| Snapmirror mis à jour 


.5+| *ora_recovery* | Briser SnapMirror 


| Activer NFS et créer un chemin de jonction pour les volumes Oracle sur le CVO de destination 


| Configurer l'hôte Oracle DR 


| Monter et vérifier les volumes Oracle 


| Récupérer et démarrer la base de données Oracle 
|===
--
====


== Paramètres par défaut

Pour simplifier l’automatisation, nous avons prédéfini de nombreux paramètres Oracle requis avec des valeurs par défaut.  Il n’est généralement pas nécessaire de modifier les paramètres par défaut pour la plupart des déploiements.  Un utilisateur plus avancé peut apporter des modifications aux paramètres par défaut avec prudence.  Les paramètres par défaut se trouvent dans chaque dossier de rôle sous le répertoire par défaut.



== Licence

Vous devez lire les informations de licence telles qu'indiquées dans le référentiel Github.  En accédant, en téléchargeant, en installant ou en utilisant le contenu de ce référentiel, vous acceptez les termes de la licence énoncéelink:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["ici"^] .

Veuillez noter qu'il existe certaines restrictions concernant la production et/ou le partage d'œuvres dérivées du contenu de ce référentiel.  Veuillez vous assurer de lire les conditions de l'link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["Licence"^] avant d'utiliser le contenu.  Si vous n'acceptez pas toutes les conditions, n'accédez pas, ne téléchargez pas et n'utilisez pas le contenu de ce référentiel.

Une fois que vous êtes prêt, cliquez surlink:db-protection-awx-automation.html["ici pour les procédures détaillées AWX/Tower"] .
